### ISSUE TITLE
"Priced Pins" string and count not appearing

### ISSUE THREAD

**Issue by ScottGerlach** [TallyApp/code#7]
Repro steps:
- Go to Pinterest board with some prices in pins
- Toggle on the Tally app at browser level (and if necessary board level)

Observe:
- The Tally is calc'd and shown [correct] but the string "Priced Pins" and its associated count does not appear [incorrect]
  ![untitled](https://cloud.githubusercontent.com/assets/10540302/7445594/21364af8-f16f-11e4-8d49-c3e0573c9e4f.png)

**Comment by voidberg** [comment]
Fixed.
